### ISSUE TITLE
Create a PURL for the ontology

### ISSUE THREAD

**Issue by cmungall** [cthoyt/wikidata-orcid-ontology#3]
Currently http://purl.obolibrary.org/obo/orcid.owl doesn't resolve

I would be fully in favor of adding this to OBO. Equally, it doesn't need to be part of OBO and it may have more success finding its own way in the semantic world.

I would lean towards registering a w3id for this. I wouldn't call it orcid though since obviously that namespace should be owned by orcid. Perhaps something like contributors, contributors2orcid, ...?

**Comment by cthoyt** [comment]
Agreed, I think doing something more generic is a better idea. I will also add an extra feature that people can request additional orcids to add

**Comment by cthoyt** [comment]
I requested a w3id PURL in https://github.com/perma-id/w3id.org/pull/3006
