### ISSUE TITLE
Link to documentation on how to import this with ODK

### ISSUE THREAD

**Issue by cthoyt** [cthoyt/wikidata-orcid-ontology#6]
@matentzn @anitacaron is there a specific tutorial on how to include ORCIDIO in ODK ontologies? If not, we should make one. Then, we should link it from the README in this repo.

**Comment by matentzn** [comment]
Lets work of this here; https://github.com/OBOAcademy/obook/pull/390

**Comment by cthoyt** [comment]
see https://oboacademy.github.io/obook/howto/odk-add-orcidio-module/
